In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/customer_churn_data.csv")

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [5]:
df.columns = df.columns.str.lower()

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.shape

(10000, 14)

### Drop unnecessary columns

In [8]:
df.drop(["rownumber", "customerid", "surname"], axis=1, inplace=True)

In [9]:
df.head()

,creditscore,geography,gender,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

### Inspect outliers or errors in numeric columns

In [10]:
df.describe()

,creditscore,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

### GEOGRAPHY

In [11]:
df["geography"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [12]:
df["geography"] = df["geography"].str.lower()

In [13]:
df["geography"].unique()

array(['france', 'spain', 'germany'], dtype=object)

In [14]:
df.rename(columns={"geography": "country"}, inplace=True)

### GENDER

In [15]:
df["gender"].unique()

array(['Female', 'Male'], dtype=object)

In [16]:
df["gender"] = df["gender"].str.lower()

In [17]:
df["gender"].unique()

array(['female', 'male'], dtype=object)

### HASCRCARD

In [18]:
df["hascrcard"].unique()

array([1, 0])

### ACTIVE MEMBER

In [19]:
df["isactivemember"].unique()

array([1, 0])

### EXITED

In [20]:
df["exited"].unique()

array([1, 0])

### Save the data

In [21]:
df.duplicated().sum()

np.int64(0)

In [23]:
df.to_csv("../data/customer_churn_processed_data.csv", index = False)

### Load the processed data

In [24]:
p_df = pd.read_csv("../data/customer_churn_processed_data.csv")

In [25]:
p_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   creditscore      10000 non-null  int64
 1   country          10000 non-null  object
 2   gender           10000 non-null  object
 3   age              10000 non-null  int64
 4   tenure           10000 non-null  int64
 5   balance          10000 non-null  float64
 6   numofproducts    10000 non-null  int64
 7   hascrcard        10000 non-null  int64
 8   isactivemember   10000 non-null  int64
 9   estimatedsalary  10000 non-null  float64
 10  exited           10000 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB